#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP response header X-Served-By

apt-get update -y
apt-get install nginx -y

# Get hostname of the server
HOSTNAME=$(hostname)

# Add custom header to nginx config
sed -i "s/# server_tokens off;/server_tokens off;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf

# Create default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart nginx
service nginx restart
