#!/usr/bin/env bash
# Installs and configures Nginx to serve "Holberton School" at root

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx start

# In case it was already running, restart to apply changes
service nginx restart
