#!/usr/bin/env bash
# Configures Nginx to serve a redirect on /redirect_me with a 301 status

apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

# Insert the redirect_me location block right after the add_header line
sed -i '/add_header X-Served-By \$hostname;/a\
\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx start
service nginx restart
